#!/bin/sh
#
# @name Aviant ATS
#
# @type Other
# @class Other
#

param set-default MAV_TYPE 0
param set-default MAV_SHL_USBONLY 0  # Allow mavlink shell over tcp

param set-default COM_RC_IN_MODE 1  # Joystick only (stops QGC complaining about setup)

param set-default SENS_BOARD_ROT 14  # Roll 180, Yaw 270

param set-default SER_TEL1_BAUD 230400
param set-default MAV_0_CONFIG 101
param set-default MAV_0_MODE 15  # ATS
param set-default MAV_0_FORWARD 1
param set-default MAV_0_RATE 0
param set-default MAV_0_RADIO_CTL 0
param set-default MAV_0_FLOW_CTRL 0

param set-default SER_TEL2_BAUD 230400
param set-default MAV_1_CONFIG 102
param set-default MAV_1_MODE 13  # Parachute
param set-default MAV_1_FORWARD 1
param set-default MAV_1_RATE 0
param set-default MAV_1_RADIO_CTL 0
param set-default MAV_1_FLOW_CTRL 0

param set-default AV_ATS_MP1_CH 13
param set-default AV_ATS_MP1_DV 21
param set-default AV_ATS_MP2_CH 2
param set-default AV_ATS_MP2_DV 21
param set-default AV_ATS_UPS_CH 14
param set-default AV_ATS_UPS_DV 2
param set-default AV_ATS_PARA_CH 3
param set-default AV_ATS_PARA_DV 11

# Nominal UPS voltage measured to 4.3v on NT06
param set-default AV_ATS_UPS_HI_V 5.5
param set-default AV_ATS_UPS_LO_V 4

# Nominal parachute voltage measured to 23.4v on NT06
param set-default AV_ATS_PARA_HI_V 25
param set-default AV_ATS_PARA_LO_V 22
